name: posix-mq test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - '0.10'
          - '0.12'
          - '4'
          - '6'
          - '8'
          - '10'
          - '12'
          - '14'
          - '16'
          - '18'

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: sudo apt install -y build-essential
      - name: Debug versions
        run: which node
      - run: node --version
      - run: which npm
      - run: npm --version
      - name: Build package
        run: npm install
      - name: Run test
        run: node test.js
